### ISSUE TITLE
Request for Update on Cytodynamics Project Development

### ISSUE THREAD

**Issue by webfolderio** [linkedin/Cytodynamics#24]
Hello,

I hope this message finds you well. I've been following the Cytodynamics project here on GitHub closely, and it seems there have not been any recent updates or additions for some time. The project is highly valuable for the community, and I'm wondering if it is still actively maintained or if there are any plans for future updates?

Given the project's impact and usefulness, it would be great to know if you have any roadmap or upcoming features that users can look forward to.

If the project is no longer being actively developed, it would be helpful for the community to know as well, so that we can look into potential alternatives or even contribute to ongoing development if that is an option.

Thank you for your time and consideration.

**Comment by jfim** [comment]
It's not really maintained anymore, as far as I understand.
